version: '3.8'

services:
  app:
    container_name: dragons-ui
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_TOSS_CLIENT_KEY: ${NEXT_PUBLIC_TOSS_CLIENT_KEY}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - SERVER_API_URL=${SERVER_API_URL:-https://dev-api.dragons.com:8083}
      - PORT=3001
    env_file:
      - .env
    restart: always
    networks:
      - default
      - nginx_net
      - uidev_net

networks:
  default:
    name: mysql_default
    external: true
  nginx_net:
    name: docker_default
    external: true
  uidev_net:
    name: uidev_default
    external: true
