version: '3.8'

services:
  app:
    container_name: dragons-ui
    # Build directly on the server (No ECR)
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_TOSS_CLIENT_KEY: ${NEXT_PUBLIC_TOSS_CLIENT_KEY}
    ports:
      # External 3000 -> Internal 3001 (Because Dockerfile has EXPOSE 3001)
      - "3000:3001"
    environment:
      - NODE_ENV=production
      - SERVER_API_URL=${SERVER_API_URL}
      # Tell Next.js to start on 3001 internally
      - PORT=3001
    restart: always
    networks:
      - default
      - nginx_net

networks:
  default:
    name: mysql_default
    external: true
  nginx_net:
    name: docker_default
    external: true
